### ISSUE TITLE
[BUG] Error when bundling with Vite: Rollup failed to resolve import "#node-web-compat"

### ISSUE THREAD

**Issue by Fitzpasd** [awslabs/aws-jwt-verify#114]
**Describe the bug**
The below error is thrown when trying to use this in an application that is bundled with [Vite](https://vitejs.dev/): 

```
[vite]: Rollup failed to resolve import "#node-web-compat" from .....
```

**Versions**
3.4.0

**To Reproduce**
[Here is a StackBlitz which shows the issue.](https://stackblitz.com/edit/vitejs-vite-dug74t?file=main.js)  Run `npm run build` in the console there and it will fail.

**Comment by Fitzpasd** [comment]
[Closing since this workaround will likely work here as well.](https://github.com/awslabs/aws-jwt-verify/issues/107#issuecomment-1382952027)

**Comment by hakanson** [comment]
I was able to compile with this `vite.config.ts` (and after a `npm install @rollup/plugin-node-resolve`)

```typescript
import { defineConfig } from 'vite';
import resolve from '@rollup/plugin-node-resolve';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [resolve({ browser: true })],
});
```

see https://stackblitz.com/edit/vitejs-vite-cpfuqa?file=vite.config.ts

**Comment by Fitzpasd** [comment]
I landed on something similar:

```
export default defineConfig({
  plugins: [resolve({ resolveOnly: ['aws-jwt-verify'] })],
});
```

For now I'm not going to switch everything over to node resolve.
