### ISSUE TITLE
NextJS TurboPack resolve #node-web-compat

### ISSUE THREAD

**Issue by rickiesmooth** [awslabs/aws-jwt-verify#122]
I'm testing turbopack with the latest version of NextJS (13.3.0) which doesn't seem to support private mappings yet. I was wondering if someone got it to work with a resolve alias?

https://turbo.build/pack/docs/features/customizing-turbopack#resolve-aliases

**Comment by ottokruse** [comment]
Closing for now because unsure how to reproduce
