### ISSUE TITLE
[BUG] --> Timeout error after 1500 ms

### ISSUE THREAD

**Issue by NavnathGunjal7** [awslabs/aws-jwt-verify#128]
**Describe the bug**
[Please provide a clear and concise description of what the bug is.]--->
(error: FetchError: Failed to fetch https://cognito-idp.ap-south-1.amazonaws.com/secrete/.well-known/jwks.json: Response time-out (after 1500 ms.))

it's from node_modules\aws-jwt-verify\dist\cjs\https-node.js:37:53)

**Versions**
Which version of `aws-jwt-verify` are you using? --> 3.4.0
Are you using the library in Node.js or in the Web browser? -->  "engines": {
    "npm": "9.6.6",
    "node": "18.13.0"
  },
If Node.js, which version of Node.js are you using? (Should be at least 14)--> Yes
If Web browser, which web browser and which version of it are you using? --> Chorme latest
If using TypeScript, which version of TypeScript are you using? (Should be at least 4) --> yes above 4

**To Reproduce**
not sure it happens sometimes but happening frequently

**Comment by ottokruse** [comment]
See this comment. If that doesn't help you let us know: https://github.com/awslabs/aws-jwt-verify/issues/72#issuecomment-1139609992
