### ISSUE TITLE
[BUG] Does not work with Bun

### ISSUE THREAD

**Issue by madsbuch** [awslabs/aws-jwt-verify#154]
This library is dysfunctional in a Bun environment.

```
TypeError: Invalid public key
      at node:crypto:77:61
      at transformJwkToKeyObjectSync (/.../node_modules/aws-jwt-verify/dist/esm/jwt-rsa.js:348:27)
      at verifyDecomposedJwtSync (/.../node_modules/aws-jwt-verify/dist/esm/jwt-rsa.js:120:23)
      at verifySync (/.../node_modules/aws-jwt-verify/dist/esm/cognito-verifier.js:94:9)
      at /.../graphQlApp.ts:41:25
```

There is a parallel bug on the Bun bug tracker: https://github.com/oven-sh/bun/issues/8004

I realize that AWS might not feel inclined to support Bun, I just want make a notice that this issue is happening.

**Comment by hakanson** [comment]
I'm curious how our unit tests in bun behave that import public keys.  In the node package.json is `"test": "npm run test:unit",` so an `npm run test` will output:

```
Test Suites: 1 skipped, 7 passed, 7 of 8 total
Tests:       4 skipped, 162 passed, 166 total
Snapshots:   0 total
Time:        29.46 s
Ran all test suites with tests matching "unit".
```

I haven't previously used bun, so dowloaded it, read https://bun.sh/guides/test/migrate-from-jest, and ran `bun test` (hoping for magic) but doesn't look like ran the same code.

```
 26 pass
 58 fail
 64 expect() calls
Ran 84 tests across 10 files. [22.44s]
```

Since you have bun experience, would you mind looking at how to run the equivalent of our unit tests?

```
    "test:unit": "jest --collect-coverage -t \"unit\" --testMatch '**/*.test.ts' --reporters=\"jest-junit\" --reporters=\"default\"",
    "test": "npm run test:unit",
```

**Comment by ottokruse** [comment]
Looks like this is our fault, see #155
But after fixing that maybe another reason pops up why this wouldn't work in Bun. Curious!

**Comment by ottokruse** [comment]
Gonna be after the weekend before we release a new version:) Bun users hold your breath

**Comment by ottokruse** [comment]
Should be fixed in v4.0.1

**Comment by ottokruse** [comment]
Let us know how you now fare with Bun @madsbuch

**Comment by ottokruse** [comment]
Ok, cool!

Any clue what is wrong with the fetcher, I see `JSON Parse error: Unexpected EOF`? Surely Bun supports JSON.parse, not sure what's wrong there

**Comment by madsbuch** [comment]
@ottokruse 

I use this implementation which is stable:

```typescript
    CognitoJwtVerifier.create(
      {
        userPoolId: config.aws.cognito.userPoolId,
        tokenUse: "access",
        clientId: config.aws.cognito.authorizedClients,
      },
      {
        jwksCache: new SimpleJwksCache({
          fetcher: {
            fetch: async (uri, req, data) =>
              (
                await fetch(uri, {
                  body: data,
                  ...req,
                })
              ).json(),
          },
        }),
      }
    )
```

I really appreciate how you have made that part pluggable. I love the "batteries included" aspect, but in particular when there are multiple runtimes (as in Bun, Node, Deno, etc.) it makes sense to hook into better solutions for each runtime,.

Anyways, I really appreciate the work here. I have fully gone back to using this package.

**Comment by ottokruse** [comment]
Cheers! And thanks for the feedback

And guess not weird that the default implementation for fetcher doesn't work, it uses the "old" NodeJS way of doing it, with eg [a pipeline](https://github.com/awslabs/aws-jwt-verify/blob/8bb9b6e4be7b9186a279a35ca82cbbed70405f55/src/https-node.ts#L47) to collect the response, which is pretty NodeJS specific (although I guess Bun would want to support that, as they strive for great compatibility). Anyway nice that you have it working now with just "fetch".
