### ISSUE TITLE
[BUG] Handle Revoked Access and ID Tokens

### ISSUE THREAD

**Issue by cjsuthanthira** [awslabs/aws-jwt-verify#173]
This library needs to return that the tokens are revoked after revoking the refresh token

**Comment by ottokruse** [comment]
Please read the explanation in https://github.com/awslabs/aws-jwt-verify/issues/151 and share any new insights. Thanks!

**Comment by ottokruse** [comment]
Why do you want this? It's very clear we could add that to this library, but why should we? Let's be more concrete: what's the threat model you're thinking of?

**Comment by ottokruse** [comment]
Thank you.

Follow up question. Where are tokens stored? Upon sign-out you should delete the tokens locally so they would not be able to be used for other apps. Why doesn't this "simply" work for you?

JWTs being stolen / leaked is another matter, but that must also be protected against while the user is still signed in--so it's not per se related to detecting sign outs right.

**Comment by ottokruse** [comment]
> we want to check the token and sign them out from these other app as well.

Do these apps use the same token storage? If yes, e.g. localstorage, then if in one app you clear the tokens from localstorage (upon signout), then other tabs can simply check token storage as well and when there's no tokens assume the user is not yet signed in. Or broadcast an event to all tabs to re-check auth status.

I presume you use the same client ID in all these apps (to use a single set of tokens across all of them), so then AWS Amplify JS would store these tokens in browser localstorage, and all your apps (for that user pool and client ID) across all tabs would actually be using the same set of items in localstorage.

**Comment by ottokruse** [comment]
> The different apps are unable to share the localStorage as they run in different sub-domains / domains.

Got it.

> Is there a way to manually set the tokens into AWS Amplify JS?

Don't know of the top of my head.

It sounds like what you're doing in the UI may be pretty specific and not a core use case to aws-jwt-verify, however backend validation surely is. What is the threat model though? Why don't you use tokens with a more limited expiry (maybe 15 minutes), and delete them upon signout? That saves you from having to do the GetUser call (which only works for access tokens) that takes additional latency and creates requests against Cognito that may hit throttling limits if too many in parallel.

Thanks for the detail so far, just trying to uncover the real reason you want to verify upstream with Cognito, what scenario's "are you afraid of" so to speak. (We can think of them ourselves but rather like to hear from you, a user)

**Comment by ottokruse** [comment]
That's probably the easiest and most scalable way!

1. Delete the tokens from the frontend upon signout
2. Sync the delete to your other apps (using a mechanism of your choosing, eg URL fragment) --> this realizes "global" sign out of your apps
3. Short token expiry --> always a good idea

**Comment by ottokruse** [comment]
Note that a sign out with Amplify JS would also call https://docs.aws.amazon.com/cognito/latest/developerguide/token-revocation.html for the refresh token (as well as delete the token locally)––which is a good idea
