### ISSUE TITLE
CognitoJwtVerifier verify function error: Expected 4 arguments, but got 1

### ISSUE THREAD

**Issue by shelou** [awslabs/aws-jwt-verify#26]
**What are the steps to reproduce this issue?**

1.  npm i aws-jwt-verify
2.  import {CognitoJwtVerifier} from "aws-jwt-verify";
3. const verifier = CognitoJwtVerifier.create({
            userPoolId: userPoolId,
            tokenUse: "id",
            clientId: clientId,
        });
4. const payload = await verifier.verify(token)

**What happens?**
verify function gives an error:   TS2554: Expected 4 arguments, but got 1

**What versions of software are you using?**
"typescript": "^3.9.10",
"ts-node": "^8.10.2",
"aws-jwt-verify": "1.0.3",   and also tried version 1.0.2

**Comment by ottokruse** [comment]
Mmm, afraid you'll need at least TypeScript 4 :|

Work around is to run in JS (not in TS) or change the `import` to a `require` but you'll loose type checking then:

```typescript
// NOT: import { CognitoJwtVerifier } from "aws-jwt-verify";
const { CognitoJwtVerifier } = require("aws-jwt-verify"); // Works, but you loose type checking
```

**Comment by ottokruse** [comment]
Or upgrade to TypeScript 4 of course for a proper solution

**Comment by ottokruse** [comment]
For consideration, it might be possible to support TypeScript 3 also, using this: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#version-selection-with-typesversions

We'll have to decide if the effort is worth the value.

**Comment by shelou** [comment]
@ottokruse thank you so much! Upgrading typescript did the job

**Comment by MudabbarHussain** [comment]
hello, I am using the CognitoJwtVerifier.create but got an error CognitoJwtVerifier.create is not a function.  kindly guide me.
code:
const verifier = CognitoJwtVerifier.create({
        userPoolId: process.env.AWS_COGNITO_USERPOOL,
        tokenUse: "access",
        clientId: process.env.AWS_COGNITO_CLIENT_ID,
      });

**Comment by ottokruse** [comment]
Please create a separate issue and provide us a complete example with which to reproduce (i.e. one that at least also shows how you import the library)
