### ISSUE TITLE
[BUG] (Not a real bug) Thanks!

### ISSUE THREAD

**Issue by teuber789** [awslabs/aws-jwt-verify#56]
Just wanted to say thanks for this slick little library! I spent a couple days wrestling with more popular JWT verification libraries, and had zero luck. I ran into tons of issues, like poor documentation, poor ES6 / Typescript support, and about every problem under the sun. I happened upon this library, and within an hour I had it up and working without any issues. It's a _dream_. Many thanks to all those working on it!

**Comment by leelalagudu** [comment]
Hi @teuber789 , many thanks for your kind words. Both @ottokruse  and I appreciate your feedback. Do let us know if you find that there are any missing features/any bugs that you come across.

Thank you,
Leela & Otto.
