### ISSUE TITLE
'alg' is an optional field in the JWK spec, but it is required by this library

### ISSUE THREAD

**Issue by jpda** [awslabs/aws-jwt-verify#6]
Microsoft's identity platform uses the `kty` parameter for the encryption family, `alg` is omitted. `alg` is optional [per rfc7517](https://datatracker.ietf.org/doc/html/rfc7517#section-4), however this library seems to require it. Seems since the alg variable is already set to "RS256," and `kty` is in the `allJwkFields` array and required per spec, that removing `alg` from the required list may be all that's required. 

The `allJwkFields` array includes `alg.`

https://github.com/awslabs/aws-jwt-verify/blob/f0531cd190f4cf9213e058b55d725a346775964d/src/jwk.ts#L21

A missing `alg` throws an error here. 

https://github.com/awslabs/aws-jwt-verify/blob/f0531cd190f4cf9213e058b55d725a346775964d/src/jwk.ts#L99-L103

example key data can be found [here](https://login.microsoftonline.com/common/discovery/v2.0/keys)

replicated below (snipped the cert data and removed some keys, as there are normally ~6-8 keys, for brevity)

```json
{
  "keys": [
    {
      "kty": "RSA",
      "use": "sig",
      "kid": "nOo3ZDrODXEK1jKWhXslHR_KXEg",
      "x5t": "nOo3ZDrODXEK1jKWhXslHR_KXEg",
      "n": "oaLLT9hkc.../snip",
      "e": "AQAB",
      "x5c": [
      "MIIDBTCCAe2g.../snip"
      ],
      "issuer": "https://login.microsoftonline.com/{tenantid}/v2.0"
    },
    {
      "kty": "RSA",
      "use": "sig",
      "kid": "l3sQ-50cCH4xBVZLHTGwnSR7680",
      "x5t": "l3sQ-50cCH4xBVZLHTGwnSR7680",
      "n": "sfsXMXWuO-.../snip",
      "e": "AQAB",
      "x5c": [
        "MIIDBTCCA.../snip"
      ],
      "issuer": "https://login.microsoftonline.com/{tenantid}/v2.0"
    }
  ]
}
```

**Comment by ottokruse** [comment]
Should work now for Microsoft JWTs too 🎉 

Please let us know any and all feedback

**Comment by cmatskas** [comment]
Tested it successfully and it’s all working as expected! Many thanks for your work on this!
