### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by yaroslavkrutiak** [awslabs/aws-jwt-verify#99]
**Question**
How can we help you?

Im trying to use verifyJwt function at aws-jwt-verify/jwt-rsa

When I run unit test it just show me this
Maybe you can help me to figure out what i am doing wrong, or you say what you'd rather use when you need to verify jwt from user pool and identity pools at same time
<img width="677" alt="Screenshot 2022-11-29 at 00 06 17" src="https://user-images.githubusercontent.com/62379398/204390859-122dcba3-f3d7-46f5-b185-f970c3c270cd.png">

**Versions**
Which version of `aws-jwt-verify` are you using?   3.2.0
Are you using the library in Node.js or in the Web browser?   Node.js
If Node.js, which version of Node.js are you using? (Should be at least 14)   18
If Web browser, which web browser and which version of it are you using?  -
If using TypeScript, which version of TypeScript are you using? (Should be at least 4)  4.8.4

**Comment by ottokruse** [comment]
Is that jest you're using as test runner? If so have a look here: #66

https://github.com/awslabs/aws-jwt-verify/issues/66

**Comment by ottokruse** [comment]
Is this resolved @yaroslavkrutiak
